import { BadRequestException, NotFoundException } from '@nestjs/common';

import {
  getCountryCallingCode,
  CountryCode,
  parsePhoneNumber,
} from 'libphonenumber-js/mobile';

export const countries = [
  {
    continent: 'Asia',
    region: 'South Asia',
    country: 'Afghanistan',
    countryAr: 'افغانستان',
    nationality: 'Afghan',
    nationalityAr: 'افغاني',
    flag: 'https://flagcdn.com/af.svg',
    capital: 'Kabul',
    fips: 'AF',
    iso2: 'AF',
    iso3: 'AFG',
    isoNo: '004',
    internet: 'AF',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'Albania',
    countryAr: 'ألبانيا',
    nationality: 'Albanian',
    nationalityAr: 'ألباني',
    flag: 'https://flagcdn.com/al.svg',
    capital: 'Tirana',
    fips: 'AL',
    iso2: 'AL',
    iso3: 'ALB',
    isoNo: '008',
    internet: 'AL',
  },
  {
    continent: 'Africa',
    region: 'Northern Africa',
    country: 'Algeria',
    countryAr: 'الجزائر',
    nationality: 'Algerian',
    nationalityAr: 'جزائري',
    flag: 'https://flagcdn.com/dz.svg',
    capital: 'Algiers',
    fips: 'AG',
    iso2: 'DZ',
    iso3: 'DZA',
    isoNo: '012',
    internet: 'DZ',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'American Samoa',
    countryAr: 'ساموا الأمريكية',
    nationality: 'American Samoan',
    nationalityAr: 'ساموي',
    flag: 'https://flagcdn.com/as.svg',
    capital: 'Pago Pago',
    fips: 'AQ',
    iso2: 'AS',
    iso3: 'ASM',
    isoNo: '016',
    internet: 'AS',
  },
  {
    continent: 'Europe',
    region: 'South West Europe',
    country: 'Andorra',
    countryAr: 'أندورا',
    nationality: 'Andorran',
    nationalityAr: 'اندوري',
    flag: 'https://flagcdn.com/ad.svg',
    capital: 'Andorra la Vella',
    fips: 'AN',
    iso2: 'AD',
    iso3: 'AND',
    isoNo: '020',
    internet: 'AD',
  },
  {
    continent: 'Africa',
    region: 'Southern Africa',
    country: 'Angola',
    countryAr: 'أنغولا',
    nationality: 'Angolan',
    nationalityAr: 'انغولي',
    flag: 'https://flagcdn.com/ao.svg',
    capital: 'Luanda',
    fips: 'AO',
    iso2: 'AO',
    iso3: 'AGO',
    isoNo: '024',
    internet: 'AO',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Anguilla',
    countryAr: 'أنغيلا',
    nationality: 'Anguillan',
    nationalityAr: 'انغيلاي',
    flag: 'https://flagcdn.com/ai.svg',
    capital: 'The Valley',
    fips: 'AV',
    iso2: 'AI',
    iso3: 'AIA',
    isoNo: '660',
    internet: 'AI',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Antigua and Barbuda',
    countryAr: 'أنتيغوا وبربودا',
    nationality: 'Antiguan, Barbudan',
    nationalityAr: 'انتيغوي, بربودي',
    flag: 'https://flagcdn.com/ag.svg',
    capital: "Saint John's",
    fips: 'AC',
    iso2: 'AG',
    iso3: 'ATG',
    isoNo: '028',
    internet: 'AG',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Argentina',
    countryAr: 'الأرجنتين',
    nationality: 'Argentinian',
    nationalityAr: 'ارجنتيني',
    flag: 'https://flagcdn.com/ar.svg',
    capital: 'Buenos Aires',
    fips: 'AR',
    iso2: 'AR',
    iso3: 'ARG',
    isoNo: '032',
    internet: 'AR',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Armenia',
    countryAr: 'أرمينيا',
    nationality: 'Armenian',
    nationalityAr: 'ارميني',
    flag: 'https://flagcdn.com/am.svg',
    capital: 'Yerevan',
    fips: 'AM',
    iso2: 'AM',
    iso3: 'ARM',
    isoNo: '051',
    internet: 'AM',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Aruba',
    countryAr: 'أروبا',
    nationality: 'Aruban',
    nationalityAr: 'اروبي',
    flag: 'https://flagcdn.com/aw.svg',
    capital: 'Oranjestad',
    fips: 'AA',
    iso2: 'AW',
    iso3: 'ABW',
    isoNo: '533',
    internet: 'AW',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Australia',
    countryAr: 'أستراليا',
    nationality: 'Australian',
    nationalityAr: 'استرالي',
    flag: 'https://flagcdn.com/au.svg',
    capital: 'Canberra',
    fips: 'AS',
    iso2: 'AU',
    iso3: 'AUS',
    isoNo: '036',
    internet: 'AU',
  },
  {
    continent: 'Europe',
    region: 'Central Europe',
    country: 'Austria',
    countryAr: 'النمسا',
    nationality: 'Austrian',
    nationalityAr: 'نمساوي',
    flag: 'https://flagcdn.com/at.svg',
    capital: 'Vienna',
    fips: 'AU',
    iso2: 'AT',
    iso3: 'AUT',
    isoNo: '040',
    internet: 'AT',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Azerbaijan',
    countryAr: 'أذربيجان',
    nationality: 'Azerbaijani',
    nationalityAr: 'اذربيجاني',
    flag: 'https://flagcdn.com/az.svg',
    capital: 'Baku (Baki)',
    fips: 'AJ',
    iso2: 'AZ',
    iso3: 'AZE',
    isoNo: '031',
    internet: 'AZ',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'The Bahamas',
    countryAr: 'الباهاما',
    nationality: 'Bahamian',
    nationalityAr: 'باهامي',
    flag: 'https://flagcdn.com/bs.svg',
    capital: 'Nassau',
    fips: 'BF',
    iso2: 'BS',
    iso3: 'BHS',
    isoNo: '044',
    internet: 'BS',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Bahrain',
    countryAr: 'البحرين',
    nationality: 'Bahraini',
    nationalityAr: 'بحريني',
    flag: 'https://flagcdn.com/bh.svg',
    capital: 'Manama',
    fips: 'BA',
    iso2: 'BH',
    iso3: 'BHR',
    isoNo: '048',
    internet: 'BH',
  },
  {
    continent: 'Asia',
    region: 'South Asia',
    country: 'Bangladesh',
    countryAr: 'بنغلاديش',
    nationality: 'Bangladeshi',
    nationalityAr: 'بنغلاديشي',
    flag: 'https://flagcdn.com/bd.svg',
    capital: 'Dhaka',
    fips: 'BG',
    iso2: 'BD',
    iso3: 'BGD',
    isoNo: '050',
    internet: 'BD',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Barbados',
    countryAr: 'بربادوس',
    nationality: 'Barbadian',
    nationalityAr: 'بربادوسي',
    flag: 'https://flagcdn.com/bb.svg',
    capital: 'Bridgetown',
    fips: 'BB',
    iso2: 'BB',
    iso3: 'BRB',
    isoNo: '052',
    internet: 'BB',
  },
  {
    continent: 'Europe',
    region: 'Eastern Europe',
    country: 'Belarus',
    countryAr: 'بيلاروسيا',
    nationality: 'Belarusian',
    nationalityAr: 'بيلاروسي',
    flag: 'https://flagcdn.com/by.svg',
    capital: 'Minsk',
    fips: 'BO',
    iso2: 'BY',
    iso3: 'BLR',
    isoNo: '112',
    internet: 'BY',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'Belgium',
    countryAr: 'بلجيكا',
    nationality: 'Belgian',
    nationalityAr: 'بلجيكي',
    flag: 'https://flagcdn.com/be.svg',
    capital: 'Brussels',
    fips: 'BE',
    iso2: 'BE',
    iso3: 'BEL',
    isoNo: '056',
    internet: 'BE',
  },
  {
    continent: 'Americas',
    region: 'Central America',
    country: 'Belize',
    countryAr: 'بليز',
    nationality: 'Belizean',
    nationalityAr: 'بليزي',
    flag: 'https://flagcdn.com/bz.svg',
    capital: 'Belmopan',
    fips: 'BH',
    iso2: 'BZ',
    iso3: 'BLZ',
    isoNo: '084',
    internet: 'BZ',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Benin',
    countryAr: 'بنين',
    nationality: 'Beninese',
    nationalityAr: 'بنيني',
    flag: 'https://flagcdn.com/bj.svg',
    capital: 'Porto-Novo',
    fips: 'BN',
    iso2: 'BJ',
    iso3: 'BEN',
    isoNo: '204',
    internet: 'BJ',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Bermuda',
    countryAr: 'برمودا',
    nationality: 'Bermudian',
    nationalityAr: 'برمودي',
    flag: 'https://flagcdn.com/bm.svg',
    capital: 'Hamilton',
    fips: 'BD',
    iso2: 'BM',
    iso3: 'BMU',
    isoNo: '060',
    internet: 'BM',
  },
  {
    continent: 'Asia',
    region: 'South Asia',
    country: 'Bhutan',
    countryAr: 'بوتان',
    nationality: 'Bhutanese',
    nationalityAr: 'بوتاني',
    flag: 'https://flagcdn.com/bt.svg',
    capital: 'Thimphu',
    fips: 'BT',
    iso2: 'BT',
    iso3: 'BTN',
    isoNo: '064',
    internet: 'BT',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Bolivia',
    countryAr: 'بوليفيا',
    nationality: 'Bolivian',
    nationalityAr: 'بوليفي',
    flag: 'https://flagcdn.com/bo.svg',
    capital: 'La Paz / Sucre',
    fips: 'BL',
    iso2: 'BO',
    iso3: 'BOL',
    isoNo: '068',
    internet: 'BO',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'Bosnia and Herzegovina',
    countryAr: 'البوسنة والهرسك',
    nationality: 'Bosnian / Herzegovinian',
    nationalityAr: 'بوسني/هرزجوفي',
    flag: 'https://flagcdn.com/ba.svg',
    capital: 'Sarajevo',
    fips: 'BK',
    iso2: 'BA',
    iso3: 'BIH',
    isoNo: '070',
    internet: 'BA',
  },
  {
    continent: 'Africa',
    region: 'Southern Africa',
    country: 'Botswana',
    countryAr: 'بوتسوانا',
    nationality: 'Botswanan',
    nationalityAr: 'بوتسواني',
    flag: 'https://flagcdn.com/bw.svg',
    capital: 'Gaborone',
    fips: 'BC',
    iso2: 'BW',
    iso3: 'BWA',
    isoNo: '072',
    internet: 'BW',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Brazil',
    countryAr: 'برازيل',
    nationality: 'Brazilian',
    nationalityAr: 'برازيلي',
    flag: 'https://flagcdn.com/br.svg',
    capital: 'Brasilia',
    fips: 'BR',
    iso2: 'BR',
    iso3: 'BRA',
    isoNo: '076',
    internet: 'BR',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'British Virgin Islands',
    countryAr: 'جزر العذراء البريطانية',
    nationality: 'British Virgin Islander',
    nationalityAr: 'جزر العذراء البريطانية',
    flag: 'https://flagcdn.com/vg.svg',
    capital: 'Road Town',
    fips: 'VI',
    iso2: 'VG',
    iso3: 'VGB',
    isoNo: '092',
    internet: 'VG',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Brunei',
    countryAr: 'بروناي',
    nationality: 'Bruneian',
    nationalityAr: 'بروني',
    flag: 'https://flagcdn.com/bn.svg',
    capital: 'Bandar Seri Begawan',
    fips: 'BX',
    iso2: 'BN',
    iso3: 'BRN',
    isoNo: '096',
    internet: 'BN',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'Bulgaria',
    countryAr: 'بلغاريا',
    nationality: 'Bulgarian',
    nationalityAr: 'بلغاري',
    flag: 'https://flagcdn.com/bg.svg',
    capital: 'Sofia',
    fips: 'BU',
    iso2: 'BG',
    iso3: 'BGR',
    isoNo: '100',
    internet: 'BG',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Burkina Faso',
    countryAr: 'بوركينا فاسو',
    nationality: 'Burkinabe',
    nationalityAr: 'بوركيني',
    flag: 'https://flagcdn.com/bf.svg',
    capital: 'Ouagadougou',
    fips: 'UV',
    iso2: 'BF',
    iso3: 'BFA',
    isoNo: '854',
    internet: 'BF',
  },
  {
    continent: 'Africa',
    region: 'Central Africa',
    country: 'Burundi',
    countryAr: 'بوروندي',
    nationality: 'Burundian',
    nationalityAr: 'بوروندي',
    flag: 'https://flagcdn.com/bi.svg',
    capital: 'Bujumbura',
    fips: 'BY',
    iso2: 'BI',
    iso3: 'BDI',
    isoNo: '108',
    internet: 'BI',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Cambodia',
    countryAr: 'كمبوديا',
    nationality: 'Cambodian',
    nationalityAr: 'كمبودي',
    flag: 'https://flagcdn.com/kh.svg',
    capital: 'Phnom Penh',
    fips: 'CB',
    iso2: 'KH',
    iso3: 'KHM',
    isoNo: '116',
    internet: 'KH',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Cameroon',
    countryAr: 'كاميرون',
    nationality: 'Cameroonian',
    nationalityAr: 'كاميروني',
    flag: 'https://flagcdn.com/cm.svg',
    capital: 'Yaounde',
    fips: 'CM',
    iso2: 'CM',
    iso3: 'CMR',
    isoNo: '120',
    internet: 'CM',
  },
  {
    continent: 'Americas',
    region: 'North America',
    country: 'Canada',
    countryAr: 'كندا',
    nationality: 'Canadian',
    nationalityAr: 'كندي',
    flag: 'https://flagcdn.com/ca.svg',
    capital: 'Ottawa',
    fips: 'CA',
    iso2: 'CA',
    iso3: 'CAN',
    isoNo: '124',
    internet: 'CA',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Cape Verde',
    countryAr: 'الرأس الأخضر',
    nationality: 'Cape Verdean',
    nationalityAr: 'كابي فيرو',
    flag: 'https://flagcdn.com/cv.svg',
    capital: 'Praia',
    fips: 'CV',
    iso2: 'CV',
    iso3: 'CPV',
    isoNo: '132',
    internet: 'CV',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Cayman Islands',
    countryAr: 'جزر كايمان',
    nationality: 'Caymanian',
    nationalityAr: 'كايماني',
    flag: 'https://flagcdn.com/ky.svg',
    capital: 'George Town',
    fips: 'CJ',
    iso2: 'KY',
    iso3: 'CYM',
    isoNo: '136',
    internet: 'KY',
  },
  {
    continent: 'Africa',
    region: 'Central Africa',
    country: 'Central African Republic',
    countryAr: 'جمهورية افريقيا الوسطى',
    nationality: 'Central African',
    nationalityAr: 'أفريقي',
    flag: 'https://flagcdn.com/cf.svg',
    capital: 'Bangui',
    fips: 'CT',
    iso2: 'CF',
    iso3: 'CAF',
    isoNo: '140',
    internet: 'CF',
  },
  {
    continent: 'Africa',
    region: 'Central Africa',
    country: 'Chad',
    countryAr: 'تشاد',
    nationality: 'Chadian',
    nationalityAr: 'تشادي',
    flag: 'https://flagcdn.com/td.svg',
    capital: "N'Djamena",
    fips: 'CD',
    iso2: 'TD',
    iso3: 'TCD',
    isoNo: '148',
    internet: 'TD',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Chile',
    countryAr: 'شيلي',
    nationality: 'Chilean',
    nationalityAr: 'شيلي',
    flag: 'https://flagcdn.com/cl.svg',
    capital: 'Santiago',
    fips: 'CI',
    iso2: 'CL',
    iso3: 'CHL',
    isoNo: '152',
    internet: 'CL',
  },
  {
    continent: 'Asia',
    region: 'East Asia',
    country: 'China',
    countryAr: 'الصين',
    nationality: 'Chinese',
    nationalityAr: 'صيني',
    flag: 'https://flagcdn.com/cn.svg',
    capital: 'Beijing',
    fips: 'CH',
    iso2: 'CN',
    iso3: 'CHN',
    isoNo: '156',
    internet: 'CN',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Christmas Island',
    countryAr: 'جزيرة الكريسماس',
    nationality: 'Christmas Island',
    nationalityAr: 'جزيرة كريسماس',
    flag: 'https://flagcdn.com/cx.svg',
    capital: 'The Settlement',
    fips: 'KT',
    iso2: 'CX',
    iso3: 'CXR',
    isoNo: '162',
    internet: 'CX',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Cocos (Keeling) Islands',
    countryAr: 'جزر كوكوس',
    nationality: 'Cocos Islander',
    nationalityAr: 'جزر كوكوس',
    flag: 'https://flagcdn.com/cc.svg',
    capital: 'West Island',
    fips: 'CK',
    iso2: 'CC',
    iso3: 'CCK',
    isoNo: '166',
    internet: 'CC',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Colombia',
    countryAr: 'كولومبيا',
    nationality: 'Colombian',
    nationalityAr: 'كولومبي',
    flag: 'https://flagcdn.com/co.svg',
    capital: 'Bogota',
    fips: 'CO',
    iso2: 'CO',
    iso3: 'COL',
    isoNo: '170',
    internet: 'CO',
  },
  {
    continent: 'Africa',
    region: 'Indian Ocean',
    country: 'Comoros',
    countryAr: 'جزر القمر',
    nationality: 'Comorian',
    nationalityAr: 'جزر القمر',
    flag: 'https://flagcdn.com/km.svg',
    capital: 'Moroni',
    fips: 'CN',
    iso2: 'KM',
    iso3: 'COM',
    isoNo: '174',
    internet: 'KM',
  },
  {
    continent: 'Africa',
    region: 'Central Africa',
    country: 'Republic of the Congo',
    countryAr: 'جمهورية كونغو',
    nationality: 'Congolese',
    nationalityAr: 'كونغولي',
    flag: 'https://flagcdn.com/cg.svg',
    capital: 'Brazzaville',
    fips: 'CF',
    iso2: 'CG',
    iso3: 'COG',
    isoNo: '178',
    internet: 'CG',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Cook Islands',
    countryAr: 'جزر كوك',
    nationality: 'Cook Islander',
    nationalityAr: 'جزر كوك',
    flag: 'https://flagcdn.com/ck.svg',
    capital: 'Avarua',
    fips: 'CW',
    iso2: 'CK',
    iso3: 'COK',
    isoNo: '184',
    internet: 'CK',
  },
  {
    continent: 'Americas',
    region: 'Central America',
    country: 'Costa Rica',
    countryAr: 'كوستاريكا',
    nationality: 'Costa Rican',
    nationalityAr: 'كوستاريكي',
    flag: 'https://flagcdn.com/cr.svg',
    capital: 'San Jose',
    fips: 'CS',
    iso2: 'CR',
    iso3: 'CRI',
    isoNo: '188',
    internet: 'CR',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: "Cote d'Ivoire",
    countryAr: 'ساحل العاج',
    nationality: 'Ivorian',
    nationalityAr: 'ساحل عاج',
    flag: 'https://flagcdn.com/ci.svg',
    capital: 'Yamoussoukro',
    fips: 'IV',
    iso2: 'CI',
    iso3: 'CIV',
    isoNo: '384',
    internet: 'CI',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'Croatia',
    countryAr: 'كرواتيا',
    nationality: 'Croatian',
    nationalityAr: 'كرواتي',
    flag: 'https://flagcdn.com/hr.svg',
    capital: 'Zagreb',
    fips: 'HR',
    iso2: 'HR',
    iso3: 'HRV',
    isoNo: '191',
    internet: 'HR',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Cuba',
    countryAr: 'كوبا',
    nationality: 'Cuban',
    nationalityAr: 'كوبي',
    flag: 'https://flagcdn.com/cu.svg',
    capital: 'Havana',
    fips: 'CU',
    iso2: 'CU',
    iso3: 'CUB',
    isoNo: '192',
    internet: 'CU',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Cyprus',
    countryAr: 'قبرص',
    nationality: 'Cypriot',
    nationalityAr: 'قبرصي',
    flag: 'https://flagcdn.com/cy.svg',
    capital: 'Nicosia',
    fips: 'CY',
    iso2: 'CY',
    iso3: 'CYP',
    isoNo: '196',
    internet: 'CY',
  },
  {
    continent: 'Europe',
    region: 'Central Europe',
    country: 'Czechia',
    countryAr: 'جمهورية التشيك',
    nationality: 'Czech',
    nationalityAr: 'تشيكي',
    flag: 'https://flagcdn.com/cz.svg',
    capital: 'Prague',
    fips: 'EZ',
    iso2: 'CZ',
    iso3: 'CZE',
    isoNo: '203',
    internet: 'CZ',
  },
  {
    continent: 'Europe',
    region: 'Northern Europe',
    country: 'Denmark',
    countryAr: 'الدنمارك',
    nationality: 'Danish',
    nationalityAr: 'دنماركي',
    flag: 'https://flagcdn.com/dk.svg',
    capital: 'Copenhagen',
    fips: 'DA',
    iso2: 'DK',
    iso3: 'DNK',
    isoNo: '208',
    internet: 'DK',
  },
  {
    continent: 'Africa',
    region: 'Eastern Africa',
    country: 'Djibouti',
    countryAr: 'جيبوتي',
    nationality: 'Djiboutian',
    nationalityAr: 'جيبوتي',
    flag: 'https://flagcdn.com/dj.svg',
    capital: 'Djibouti',
    fips: 'DJ',
    iso2: 'DJ',
    iso3: 'DJI',
    isoNo: '262',
    internet: 'DJ',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Dominica',
    countryAr: 'دومينيكا',
    nationality: 'Dominican',
    nationalityAr: 'دومينيكي',
    flag: 'https://flagcdn.com/dm.svg',
    capital: 'Roseau',
    fips: 'DO',
    iso2: 'DM',
    iso3: 'DMA',
    isoNo: '212',
    internet: 'DM',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Dominican Republic',
    countryAr: 'جمهورية الدومينيكان',
    nationality: 'Dominican',
    nationalityAr: 'دومينيكي',
    flag: 'https://flagcdn.com/do.svg',
    capital: 'Santo Domingo',
    fips: 'DR',
    iso2: 'DO',
    iso3: 'DOM',
    isoNo: '214',
    internet: 'DO',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Ecuador',
    countryAr: 'الاكوادور',
    nationalityAr: 'اكوادوري',
    nationality: 'Ecuadorian',
    flag: 'https://flagcdn.com/ec.svg',
    capital: 'Quito',
    fips: 'EC',
    iso2: 'EC',
    iso3: 'ECU',
    isoNo: '218',
    internet: 'EC',
  },
  {
    continent: 'Africa',
    region: 'Northern Africa',
    country: 'Egypt',
    countryAr: 'مصر',
    nationality: 'Egyptian',
    nationalityAr: 'مصري',
    flag: 'https://flagcdn.com/eg.svg',
    capital: 'Cairo',
    fips: 'EG',
    iso2: 'EG',
    iso3: 'EGY',
    isoNo: '818',
    internet: 'EG',
  },
  {
    continent: 'Americas',
    region: 'Central America',
    country: 'El Salvador',
    countryAr: 'السلفادور',
    nationality: 'Salvadoran',
    nationalityAr: 'سلفادوري',
    flag: 'https://flagcdn.com/sv.svg',
    capital: 'San Salvador',
    fips: 'ES',
    iso2: 'SV',
    iso3: 'SLV',
    isoNo: '222',
    internet: 'SV',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Equatorial Guinea',
    countryAr: 'غينيا الاستوائية',
    nationality: 'Equatorial Guinean',
    nationalityAr: 'غينيا الاستوائي',
    flag: 'https://flagcdn.com/gq.svg',
    capital: 'Malabo',
    fips: 'EK',
    iso2: 'GQ',
    iso3: 'GNQ',
    isoNo: '226',
    internet: 'GQ',
  },
  {
    continent: 'Africa',
    region: 'Eastern Africa',
    country: 'Eritrea',
    countryAr: 'اريتريا',
    nationality: 'Eritrean',
    nationalityAr: 'اريتري',
    flag: 'https://flagcdn.com/er.svg',
    capital: 'Asmara',
    fips: 'ER',
    iso2: 'ER',
    iso3: 'ERI',
    isoNo: '232',
    internet: 'ER',
  },
  {
    continent: 'Europe',
    region: 'Eastern Europe',
    country: 'Estonia',
    countryAr: 'استونيا',
    nationality: 'Estonian',
    nationalityAr: 'استوني',
    flag: 'https://flagcdn.com/ee.svg',
    capital: 'Tallinn',
    fips: 'EN',
    iso2: 'EE',
    iso3: 'EST',
    isoNo: '233',
    internet: 'EE',
  },
  {
    continent: 'Africa',
    region: 'Eastern Africa',
    country: 'Ethiopia',
    countryAr: 'إثيوبيا',
    nationality: 'Ethiopian',
    nationalityAr: 'إثيوبي',
    flag: 'https://flagcdn.com/et.svg',
    capital: 'Addis Ababa',
    fips: 'ET',
    iso2: 'ET',
    iso3: 'ETH',
    isoNo: '231',
    internet: 'ET',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Falkland Islands (Islas Malvinas)',
    countryAr: 'جزر فوكلاند',
    nationality: 'Falkland Islander',
    nationalityAr: 'جزر فوكلاند',
    flag: 'https://flagcdn.com/fk.svg',
    capital: 'Stanley',
    fips: 'FA',
    iso2: 'FK',
    iso3: 'FLK',
    isoNo: '238',
    internet: 'FK',
  },
  {
    continent: 'Europe',
    region: 'Northern Europe',
    country: 'Faroe Islands',
    countryAr: 'جزر فارو',
    nationality: 'Faroese',
    nationalityAr: 'فاروي',
    capital: 'Torshavn',
    flag: 'https://flagcdn.com/fo.svg',
    fips: 'FO',
    iso2: 'FO',
    iso3: 'FRO',
    isoNo: '234',
    internet: 'FO',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Fiji',
    countryAr: 'فيجي',
    nationality: 'Fijian',
    nationalityAr: 'فيجي',
    flag: 'https://flagcdn.com/fj.svg',
    capital: 'Suva',
    fips: 'FJ',
    iso2: 'FJ',
    iso3: 'FJI',
    isoNo: '242',
    internet: 'FJ',
  },
  {
    continent: 'Europe',
    region: 'Northern Europe',
    country: 'Finland',
    countryAr: 'فنلندا',
    nationality: 'Finnish',
    nationalityAr: 'فنلندي',
    flag: 'https://flagcdn.com/fi.svg',
    capital: 'Helsinki',
    fips: 'FI',
    iso2: 'FI',
    iso3: 'FIN',
    isoNo: '246',
    internet: 'FI',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'France',
    countryAr: 'فرنسا',
    nationality: 'French',
    nationalityAr: 'فرنسي',
    flag: 'https://flagcdn.com/fr.svg',
    capital: 'Paris',
    fips: 'FR',
    iso2: 'FR',
    iso3: 'FRA',
    isoNo: '250',
    internet: 'FR',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'French Guiana',
    countryAr: 'غويانا الفرنسية',
    nationality: 'French Guianese',
    nationalityAr: 'غوياني فرنسي',
    flag: 'https://flagcdn.com/gf.svg',
    capital: 'Cayenne',
    fips: 'FG',
    iso2: 'GF',
    iso3: 'GUF',
    isoNo: '254',
    internet: 'GF',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'French Polynesia',
    countryAr: 'بولينيزيا الفرنسية',
    nationality: 'French Polynesian',
    nationalityAr: 'بولينيزي',
    flag: 'https://flagcdn.com/pf.svg',
    capital: 'Papeete',
    fips: 'FP',
    iso2: 'PF',
    iso3: 'PYF',
    isoNo: '258',
    internet: 'PF',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Gabon',
    countryAr: 'الجابون',
    nationality: 'Gabonese',
    nationalityAr: 'جابوني',
    flag: 'https://flagcdn.com/ga.svg',
    capital: 'Libreville',
    fips: 'GB',
    iso2: 'GA',
    iso3: 'GAB',
    isoNo: '266',
    internet: 'GA',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'The Gambia',
    countryAr: 'غامبيا',
    nationality: 'Gambian',
    nationalityAr: 'غامبي',
    flag: 'https://flagcdn.com/gm.svg',
    capital: 'Banjul',
    fips: 'GA',
    iso2: 'GM',
    iso3: 'GMB',
    isoNo: '270',
    internet: 'GM',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Georgia',
    countryAr: 'جورجيا',
    nationality: 'Georgian',
    nationalityAr: 'جورجي',
    flag: 'https://flagcdn.com/ge.svg',
    capital: "T'bilisi",
    fips: 'GG',
    iso2: 'GE',
    iso3: 'GEO',
    isoNo: '268',
    internet: 'GE',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'Germany',
    countryAr: 'المانيا',
    nationality: 'German',
    nationalityAr: 'الماني',
    flag: 'https://flagcdn.com/de.svg',
    capital: 'Berlin',
    fips: 'GM',
    iso2: 'DE',
    iso3: 'DEU',
    isoNo: '276',
    internet: 'DE',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Ghana',
    countryAr: 'غانا',
    nationality: 'Ghanaian',
    nationalityAr: 'غاني',
    flag: 'https://flagcdn.com/gh.svg',
    capital: 'Accra',
    fips: 'GH',
    iso2: 'GH',
    iso3: 'GHA',
    isoNo: '288',
    internet: 'GH',
  },
  {
    continent: 'Europe',
    region: 'South West Europe',
    country: 'Gibraltar',
    countryAr: 'جبل طارق',
    nationality: 'Gibraltar',
    nationalityAr: 'جبل طارق',
    flag: 'https://flagcdn.com/gi.svg',
    capital: 'Gibraltar',
    fips: 'GI',
    iso2: 'GI',
    iso3: 'GIB',
    isoNo: '292',
    internet: 'GI',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'Greece',
    countryAr: 'اليونان',
    nationality: 'Greek',
    nationalityAr: 'يوناني',
    flag: 'https://flagcdn.com/gr.svg',
    capital: 'Athens',
    fips: 'GR',
    iso2: 'GR',
    iso3: 'GRC',
    isoNo: '300',
    internet: 'GR',
  },
  {
    continent: 'Americas',
    region: 'North America',
    country: 'Greenland',
    countryAr: 'جرينلاند',
    nationality: 'Greenlandic',
    nationalityAr: 'جرينلاندي',
    flag: 'https://flagcdn.com/gl.svg',
    capital: 'Nuuk (Godthab)',
    fips: 'GL',
    iso2: 'GL',
    iso3: 'GRL',
    isoNo: '304',
    internet: 'GL',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Grenada',
    countryAr: 'غرينادا',
    nationality: 'Grenadian',
    nationalityAr: 'غرينادي',
    flag: 'https://flagcdn.com/gd.svg',
    capital: "Saint George's",
    fips: 'GJ',
    iso2: 'GD',
    iso3: 'GRD',
    isoNo: '308',
    internet: 'GD',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Guadeloupe',
    countryAr: 'جوادلوب',
    nationality: 'Guadeloupean',
    nationalityAr: 'جوادلوبي',
    flag: 'https://flagcdn.com/gp.svg',
    capital: 'Basse-Terre',
    fips: 'GP',
    iso2: 'GP',
    iso3: 'GLP',
    isoNo: '312',
    internet: 'GP',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Guam',
    countryAr: 'جوام',
    nationality: 'Guamanian',
    nationalityAr: 'جوامي',
    flag: 'https://flagcdn.com/gu.svg',
    capital: 'Hagatna (Agana)',
    fips: 'GQ',
    iso2: 'GU',
    iso3: 'GUM',
    isoNo: '316',
    internet: 'GU',
  },
  {
    continent: 'Americas',
    region: 'Central America',
    country: 'Guatemala',
    countryAr: 'غواتيمالا',
    nationality: 'Guatemalan',
    nationalityAr: 'غواتيمالي',
    flag: 'https://flagcdn.com/gt.svg',
    capital: 'Guatemala',
    fips: 'GT',
    iso2: 'GT',
    iso3: 'GTM',
    isoNo: '320',
    internet: 'GT',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Guinea',
    countryAr: 'غينيا',
    nationality: 'Guinean',
    nationalityAr: 'غيني',
    flag: 'https://flagcdn.com/gn.svg',
    capital: 'Conakry',
    fips: 'GV',
    iso2: 'GN',
    iso3: 'GIN',
    isoNo: '324',
    internet: 'GN',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Guinea-Bissau',
    countryAr: 'غينيا بيساو',
    nationality: 'Guinea-Bissauan',
    nationalityAr: 'غينيا بيساوي',
    flag: 'https://flagcdn.com/gw.svg',
    capital: 'Bissau',
    fips: 'PU',
    iso2: 'GW',
    iso3: 'GNB',
    isoNo: '624',
    internet: 'GW',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Guyana',
    countryAr: 'غيانا',
    nationality: 'Guyanese',
    nationalityAr: 'غياني',
    flag: 'https://flagcdn.com/gy.svg',
    capital: 'Georgetown',
    fips: 'GY',
    iso2: 'GY',
    iso3: 'GUY',
    isoNo: '328',
    internet: 'GY',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Haiti',
    countryAr: 'هايتي',
    nationality: 'Haitian',
    nationalityAr: 'هايتي',
    flag: 'https://flagcdn.com/ht.svg',
    capital: 'Port-au-Prince',
    fips: 'HA',
    iso2: 'HT',
    iso3: 'HTI',
    isoNo: '332',
    internet: 'HT',
  },
  {
    continent: 'Europe',
    region: 'Southern Europe',
    country: 'Holy See (Vatican City)',
    countryAr: 'الفاتيكان',
    nationality: 'Vatican',
    nationalityAr: 'فاتيكاني',
    flag: 'https://flagcdn.com/va.svg',
    capital: 'Vatican City',
    fips: 'VT',
    iso2: 'VA',
    iso3: 'VAT',
    isoNo: '336',
    internet: 'VA',
  },
  {
    continent: 'Americas',
    region: 'Central America',
    country: 'Honduras',
    countryAr: 'هندوراس',
    nationality: 'Honduran',
    nationalityAr: 'هندوراسي',
    flag: 'https://flagcdn.com/hn.svg',
    capital: 'Tegucigalpa',
    fips: 'HO',
    iso2: 'HN',
    iso3: 'HND',
    isoNo: '340',
    internet: 'HN',
  },
  {
    continent: 'Europe',
    region: 'Central Europe',
    country: 'Hungary',
    countryAr: 'المجر',
    nationality: 'Hungarian',
    nationalityAr: 'مجري',
    flag: 'https://flagcdn.com/hu.svg',
    capital: 'Budapest',
    fips: 'HU',
    iso2: 'HU',
    iso3: 'HUN',
    isoNo: '348',
    internet: 'HU',
  },
  {
    continent: 'Europe',
    region: 'Northern Europe',
    country: 'Iceland',
    countryAr: 'آيسلندا',
    nationality: 'Icelander',
    nationalityAr: 'آيسلندي',
    flag: 'https://flagcdn.com/is.svg',
    capital: 'Reykjavik',
    fips: 'IC',
    iso2: 'IS',
    iso3: 'ISL',
    isoNo: '352',
    internet: 'IS',
  },
  {
    continent: 'Asia',
    region: 'South Asia',
    country: 'India',
    countryAr: 'الهند',
    nationality: 'Indian',
    nationalityAr: 'هندي',
    flag: 'https://flagcdn.com/in.svg',
    capital: 'New Delhi',
    fips: 'IN',
    iso2: 'IN',
    iso3: 'IND',
    isoNo: '356',
    internet: 'IN',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Indonesia',
    countryAr: 'اندونيسيا',
    nationality: 'Indonesian',
    nationalityAr: 'اندونيسي',
    flag: 'https://flagcdn.com/id.svg',
    capital: 'Jakarta',
    fips: 'ID',
    iso2: 'ID',
    iso3: 'IDN',
    isoNo: '360',
    internet: 'ID',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Iran',
    countryAr: 'ايران',
    nationality: 'Iranian',
    nationalityAr: 'ايراني',
    flag: 'https://flagcdn.com/ir.svg',
    capital: 'Tehran',
    fips: 'IR',
    iso2: 'IR',
    iso3: 'IRN',
    isoNo: '364',
    internet: 'IR',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Iraq',
    countryAr: 'العراق',
    nationality: 'Iraqi',
    nationalityAr: 'عراقي',
    flag: 'https://flagcdn.com/iq.svg',
    capital: 'Baghdad',
    fips: 'IZ',
    iso2: 'IQ',
    iso3: 'IRQ',
    isoNo: '368',
    internet: 'IQ',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'Ireland',
    countryAr: 'ايرلندا',
    nationality: 'Irish',
    nationalityAr: 'ايرلندي',
    flag: 'https://flagcdn.com/ie.svg',
    capital: 'Dublin',
    fips: 'EI',
    iso2: 'IE',
    iso3: 'IRL',
    isoNo: '372',
    internet: 'IE',
  },
  {
    continent: 'Europe',
    region: 'Southern Europe',
    country: 'Italy',
    countryAr: 'ايطاليا',
    nationality: 'Italian',
    nationalityAr: 'ايطالي',
    flag: 'https://flagcdn.com/it.svg',
    capital: 'Rome',
    fips: 'IT',
    iso2: 'IT',
    iso3: 'ITA',
    isoNo: '380',
    internet: 'IT',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Jamaica',
    countryAr: 'جامايكا',
    nationality: 'Jamaican',
    nationalityAr: 'جامايكي',
    flag: 'https://flagcdn.com/jm.svg',
    capital: 'Kingston',
    fips: 'JM',
    iso2: 'JM',
    iso3: 'JAM',
    isoNo: '388',
    internet: 'JM',
  },
  {
    continent: 'Asia',
    region: 'East Asia',
    country: 'Japan',
    countryAr: 'اليابان',
    nationality: 'Japanese',
    nationalityAr: 'ياباني',
    flag: 'https://flagcdn.com/jp.svg',
    capital: 'Tokyo',
    fips: 'JA',
    iso2: 'JP',
    iso3: 'JPN',
    isoNo: '392',
    internet: 'JP',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Jordan',
    countryAr: 'الاردن',
    nationality: 'Jordanian',
    nationalityAr: 'اردني',
    flag: 'https://flagcdn.com/jo.svg',
    capital: 'Amman',
    fips: 'JO',
    iso2: 'JO',
    iso3: 'JOR',
    isoNo: '400',
    internet: 'JO',
  },
  {
    continent: 'Asia',
    region: 'Central Asia',
    country: 'Kazakhstan',
    countryAr: 'كازاخستان',
    nationality: 'Kazakhstani',
    nationalityAr: 'كازاخستاني',
    flag: 'https://flagcdn.com/kz.svg',
    capital: 'Astana (Akmola)',
    fips: 'KZ',
    iso2: 'KZ',
    iso3: 'KAZ',
    isoNo: '398',
    internet: 'KZ',
  },
  {
    continent: 'Africa',
    region: 'Eastern Africa',
    country: 'Kenya',
    countryAr: 'كينيا',
    nationality: 'Kenyan',
    nationalityAr: 'كيني',
    flag: 'https://flagcdn.com/ke.svg',
    capital: 'Nairobi',
    fips: 'KE',
    iso2: 'KE',
    iso3: 'KEN',
    isoNo: '404',
    internet: 'KE',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Kiribati',
    countryAr: 'كيريباتي',
    nationality: 'I-Kiribati',
    nationalityAr: 'كيريباتي',
    flag: 'https://flagcdn.com/ki.svg',
    capital: 'Tarawa',
    fips: 'KR',
    iso2: 'KI',
    iso3: 'KIR',
    isoNo: '296',
    internet: 'KI',
  },
  {
    continent: 'Asia',
    region: 'East Asia',
    country: 'North Korea',
    countryAr: 'كوريا الشمالية',
    nationality: 'North Korean',
    nationalityAr: 'كوري شمالي',
    flag: 'https://flagcdn.com/kp.svg',
    capital: "P'yongyang",
    fips: 'KN',
    iso2: 'KP',
    iso3: 'PRK',
    isoNo: '408',
    internet: 'KP',
  },
  {
    continent: 'Asia',
    region: 'East Asia',
    country: 'South Korea',
    countryAr: 'كوريا الجنوبية',
    nationality: 'South Korean',
    nationalityAr: 'كوري جنوبي',
    flag: 'https://flagcdn.com/kr.svg',
    capital: 'Seoul',
    fips: 'KS',
    iso2: 'KR',
    iso3: 'KOR',
    isoNo: '410',
    internet: 'KR',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Kuwait',
    countryAr: 'الكويت',
    nationality: 'Kuwaiti',
    nationalityAr: 'كويتي',
    flag: 'https://flagcdn.com/kw.svg',
    capital: 'Kuwait',
    fips: 'KU',
    iso2: 'KW',
    iso3: 'KWT',
    isoNo: '414',
    internet: 'KW',
  },
  {
    continent: 'Asia',
    region: 'Central Asia',
    country: 'Kyrgyzstan',
    countryAr: 'قيرغيزستان',
    nationality: 'Kyrgyzstani',
    nationalityAr: 'قيرغيزستاني',
    flag: 'https://flagcdn.com/kg.svg',
    capital: 'Bishkek',
    fips: 'KG',
    iso2: 'KG',
    iso3: 'KGZ',
    isoNo: '417',
    internet: 'KG',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Laos',
    countryAr: 'لاوس',
    nationality: 'Laotian',
    nationalityAr: 'لاوسي',
    flag: 'https://flagcdn.com/la.svg',
    capital: 'Vientiane',
    fips: 'LA',
    iso2: 'LA',
    iso3: 'LAO',
    isoNo: '418',
    internet: 'LA',
  },
  {
    continent: 'Europe',
    region: 'Eastern Europe',
    country: 'Latvia',
    countryAr: 'لاتفيا',
    nationality: 'Latvian',
    nationalityAr: 'لاتفي',
    flag: 'https://flagcdn.com/lv.svg',
    capital: 'Riga',
    fips: 'LG',
    iso2: 'LV',
    iso3: 'LVA',
    isoNo: '428',
    internet: 'LV',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Lebanon',
    countryAr: 'لبنان',
    nationality: 'Lebanese',
    nationalityAr: 'لبناني',
    flag: 'https://flagcdn.com/lb.svg',
    capital: 'Beirut',
    fips: 'LE',
    iso2: 'LB',
    iso3: 'LBN',
    isoNo: '422',
    internet: 'LB',
  },
  {
    continent: 'Africa',
    region: 'Southern Africa',
    country: 'Lesotho',
    countryAr: 'ليسوتو',
    nationality: 'Lesotho',
    nationalityAr: 'ليسوتي',
    flag: 'https://flagcdn.com/ls.svg',
    capital: 'Maseru',
    fips: 'LT',
    iso2: 'LS',
    iso3: 'LSO',
    isoNo: '426',
    internet: 'LS',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Liberia',
    nationality: 'Liberian',
    countryAr: 'ليبيريا',
    nationalityAr: 'ليبيري',
    flag: 'https://flagcdn.com/lr.svg',
    capital: 'Monrovia',
    fips: 'LI',
    iso2: 'LR',
    iso3: 'LBR',
    isoNo: '430',
    internet: 'LR',
  },
  {
    continent: 'Africa',
    region: 'Northern Africa',
    country: 'Libya',
    countryAr: 'ليبيا',
    nationality: 'Libyan',
    nationalityAr: 'ليبي',
    flag: 'https://flagcdn.com/ly.svg',
    capital: 'Tripoli',
    fips: 'LY',
    iso2: 'LY',
    iso3: 'LBY',
    isoNo: '434',
    internet: 'LY',
  },
  {
    continent: 'Europe',
    region: 'Central Europe',
    country: 'Liechtenstein',
    countryAr: 'ليختنشتاين',
    nationality: 'Liechtensteiner',
    nationalityAr: 'ليختنشتايني',
    flag: 'https://flagcdn.com/li.svg',
    capital: 'Vaduz',
    fips: 'LS',
    iso2: 'LI',
    iso3: 'LIE',
    isoNo: '438',
    internet: 'LI',
  },
  {
    continent: 'Europe',
    region: 'Eastern Europe',
    country: 'Lithuania',
    countryAr: 'ليتوانيا',
    nationality: 'Lithuanian',
    nationalityAr: 'ليتواني',
    flag: 'https://flagcdn.com/lt.svg',
    capital: 'Vilnius',
    fips: 'LH',
    iso2: 'LT',
    iso3: 'LTU',
    isoNo: '440',
    internet: 'LT',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'Luxembourg',
    countryAr: 'لوكسمبورغ',
    nationality: 'Luxembourgish',
    nationalityAr: 'لوكسمبورغي',
    flag: 'https://flagcdn.com/lu.svg',
    capital: 'Luxembourg',
    fips: 'LU',
    iso2: 'LU',
    iso3: 'LUX',
    isoNo: '442',
    internet: 'LU',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'North Macedonia',
    countryAr: 'مقدونيا الشمالية',
    nationality: 'Macedonian',
    nationalityAr: 'مقدوني',
    flag: 'https://flagcdn.com/mk.svg',
    capital: 'Skopje',
    fips: 'MK',
    iso2: 'MK',
    iso3: 'MKD',
    isoNo: '807',
    internet: 'MK',
  },
  {
    continent: 'Africa',
    region: 'Indian Ocean',
    country: 'Madagascar',
    countryAr: 'مدغشقر',
    nationality: 'Malagasy',
    nationalityAr: 'مدغشقري',
    flag: 'https://flagcdn.com/mg.svg',
    capital: 'Antananarivo',
    fips: 'MA',
    iso2: 'MG',
    iso3: 'MDG',
    isoNo: '450',
    internet: 'MG',
  },
  {
    continent: 'Africa',
    region: 'Southern Africa',
    country: 'Malawi',
    countryAr: 'مالاوي',
    nationality: 'Malawian',
    nationalityAr: 'مالاوي',
    flag: 'https://flagcdn.com/mw.svg',
    capital: 'Lilongwe',
    fips: 'MI',
    iso2: 'MW',
    iso3: 'MWI',
    isoNo: '454',
    internet: 'MW',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Malaysia',
    countryAr: 'ماليزيا',
    nationality: 'Malaysian',
    nationalityAr: 'ماليزي',
    flag: 'https://flagcdn.com/my.svg',
    capital: 'Kuala Lumpur',
    fips: 'MY',
    iso2: 'MY',
    iso3: 'MYS',
    isoNo: '458',
    internet: 'MY',
  },
  {
    continent: 'Asia',
    region: 'South Asia',
    country: 'Maldives',
    countryAr: 'جزر المالديف',
    nationality: 'Maldivian',
    nationalityAr: 'مالديفي',
    flag: 'https://flagcdn.com/mv.svg',
    capital: 'Male (Maale)',
    fips: 'MV',
    iso2: 'MV',
    iso3: 'MDV',
    isoNo: '462',
    internet: 'MV',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Mali',
    countryAr: 'مالي',
    nationality: 'Malian',
    nationalityAr: 'مالي',
    flag: 'https://flagcdn.com/ml.svg',
    capital: 'Bamako',
    fips: 'ML',
    iso2: 'ML',
    iso3: 'MLI',
    isoNo: '466',
    internet: 'ML',
  },
  {
    continent: 'Europe',
    region: 'Southern Europe',
    country: 'Malta',
    countryAr: 'مالطا',
    nationality: 'Maltese',
    nationalityAr: 'مالطي',
    flag: 'https://flagcdn.com/mt.svg',
    capital: 'Valletta',
    fips: 'MT',
    iso2: 'MT',
    iso3: 'MLT',
    isoNo: '470',
    internet: 'MT',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'Isle of Man',
    countryAr: 'جزيرة مان',
    nationality: 'Manx',
    nationalityAr: 'مانكس',
    flag: 'https://flagcdn.com/im.svg',
    capital: 'Douglas',
    fips: 'IM',
    iso2: 'IM',
    iso3: 'IMN',
    isoNo: '833',
    internet: 'IM',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Marshall Islands',
    countryAr: 'جزر مارشال',
    nationality: 'Marshallese',
    nationalityAr: 'مارشالي',
    flag: 'https://flagcdn.com/mh.svg',
    capital: 'Majuro',
    fips: 'RM',
    iso2: 'MH',
    iso3: 'MHL',
    isoNo: '584',
    internet: 'MH',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Martinique',
    countryAr: 'مارتينيك',
    nationality: 'Martiniquais',
    nationalityAr: 'مارتينيكي',
    flag: 'https://flagcdn.com/mq.svg',
    capital: 'Fort-de-France',
    fips: 'MB',
    iso2: 'MQ',
    iso3: 'MTQ',
    isoNo: '474',
    internet: 'MQ',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Mauritania',
    countryAr: 'موريتانيا',
    nationality: 'Mauritanian',
    nationalityAr: 'موريتاني',
    flag: 'https://flagcdn.com/mr.svg',
    capital: 'Nouakchott',
    fips: 'MR',
    iso2: 'MR',
    iso3: 'MRT',
    isoNo: '478',
    internet: 'MR',
  },
  {
    continent: 'Africa',
    region: 'Indian Ocean',
    country: 'Mauritius',
    countryAr: 'موريشيوس',
    nationality: 'Mauritian',
    nationalityAr: 'موريشي',
    flag: 'https://flagcdn.com/mu.svg',
    capital: 'Port Louis',
    fips: 'MP',
    iso2: 'MU',
    iso3: 'MUS',
    isoNo: '480',
    internet: 'MU',
  },
  {
    continent: 'Africa',
    region: 'Indian Ocean',
    country: 'Mayotte',
    countryAr: 'مايوت',
    nationality: 'Mahoran',
    nationalityAr: 'مايوتي',
    flag: 'https://flagcdn.com/yt.svg',
    capital: 'Mamoutzou',
    fips: 'MF',
    iso2: 'YT',
    iso3: 'MYT',
    isoNo: '175',
    internet: 'YT',
  },
  {
    continent: 'Americas',
    region: 'Central America',
    country: 'Mexico',
    countryAr: 'المكسيك',
    nationalityAr: 'مكسيكي',
    nationality: 'Mexican',
    flag: 'https://flagcdn.com/mx.svg',
    capital: 'Mexico',
    fips: 'MX',
    iso2: 'MX',
    iso3: 'MEX',
    isoNo: '484',
    internet: 'MX',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Federated States of Micronesia',
    countryAr: 'ولايات ميكرونيسيا المتحدة',
    nationality: 'Micronesian',
    nationalityAr: 'ميكرونيسي',
    flag: 'https://flagcdn.com/fm.svg',
    capital: 'Palikir',
    fips: '',
    iso2: 'FM',
    iso3: 'FSM',
    isoNo: '583',
    internet: 'FM',
  },
  {
    continent: 'Europe',
    region: 'Eastern Europe',
    country: 'Moldova',
    countryAr: 'مولدوفا',
    nationality: 'Moldovan',
    nationalityAr: 'مولدوفي',
    flag: 'https://flagcdn.com/md.svg',
    capital: 'Chisinau',
    fips: 'MD',
    iso2: 'MD',
    iso3: 'MDA',
    isoNo: '498',
    internet: 'MD',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'Monaco',
    countryAr: 'موناكو',
    nationality: 'Monegasque',
    nationalityAr: 'موناكي',
    flag: 'https://flagcdn.com/mc.svg',
    capital: 'Monaco',
    fips: 'MN',
    iso2: 'MC',
    iso3: 'MCO',
    isoNo: '492',
    internet: 'MC',
  },
  {
    continent: 'Asia',
    region: 'Northern Asia',
    country: 'Mongolia',
    countryAr: 'منغوليا',
    nationality: 'Mongolian',
    nationalityAr: 'منغولي',
    flag: 'https://flagcdn.com/mn.svg',
    capital: 'Ulaanbaatar',
    fips: 'MG',
    iso2: 'MN',
    iso3: 'MNG',
    isoNo: '496',
    internet: 'MN',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Montserrat',
    countryAr: 'مونتسرات',
    nationality: 'Montserratian',
    nationalityAr: 'مونتسراتي',
    flag: 'https://flagcdn.com/ms.svg',
    capital: 'Plymouth',
    fips: 'MH',
    iso2: 'MS',
    iso3: 'MSR',
    isoNo: '500',
    internet: 'MS',
  },
  {
    continent: 'Africa',
    region: 'Northern Africa',
    country: 'Morocco',
    countryAr: 'المغرب',
    nationality: 'Moroccan',
    nationalityAr: 'مغربي',
    flag: 'https://flagcdn.com/ma.svg',
    capital: 'Rabat',
    fips: 'MO',
    iso2: 'MA',
    iso3: 'MAR',
    isoNo: '504',
    internet: 'MA',
  },
  {
    continent: 'Africa',
    region: 'Southern Africa',
    country: 'Mozambique',
    countryAr: 'موزمبيق',
    nationality: 'Mozambican',
    nationalityAr: 'موزمبيقي',
    flag: 'https://flagcdn.com/mz.svg',
    capital: 'Maputo',
    fips: 'MZ',
    iso2: 'MZ',
    iso3: 'MOZ',
    isoNo: '508',
    internet: 'MZ',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Myanmar (Burma)',
    countryAr: 'ميانمار',
    nationality: 'Burmese',
    nationalityAr: 'بورمي',
    flag: 'https://flagcdn.com/mm.svg',
    capital: 'Rangoon (Yangon)',
    fips: 'BM',
    iso2: 'MM',
    iso3: 'MMR',
    isoNo: '104',
    internet: 'MM',
  },
  {
    continent: 'Africa',
    region: 'Southern Africa',
    country: 'Namibia',
    countryAr: 'ناميبيا',
    nationality: 'Namibian',
    nationalityAr: 'ناميبي',
    flag: 'https://flagcdn.com/na.svg',
    capital: 'Windhoek',
    fips: 'WA',
    iso2: 'NA',
    iso3: 'NAM',
    isoNo: '516',
    internet: 'NA',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Nauru',
    countryAr: 'ناورو',
    nationality: 'Nauruan',
    nationalityAr: 'ناوروي',
    flag: 'https://flagcdn.com/nr.svg',
    capital: 'no official capital',
    fips: 'NR',
    iso2: 'NR',
    iso3: 'NRU',
    isoNo: '520',
    internet: 'NR',
  },
  {
    continent: 'Asia',
    region: 'South Asia',
    country: 'Nepal',
    countryAr: 'نيبال',
    nationality: 'Nepalese',
    nationalityAr: 'نيبالي',
    flag: 'https://flagcdn.com/np.svg',
    capital: 'Kathmandu',
    fips: 'NP',
    iso2: 'NP',
    iso3: 'NPL',
    isoNo: '524',
    internet: 'NP',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'Netherlands',
    countryAr: 'هولندا',
    nationality: 'Dutch',
    nationalityAr: 'هولندي',
    flag: 'https://flagcdn.com/nl.svg',
    capital: 'Amsterdam',
    fips: 'NL',
    iso2: 'NL',
    iso3: 'NLD',
    isoNo: '528',
    internet: 'NL',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Netherlands Antilles',
    countryAr: 'جزر الانتيل الهولندية',
    nationality: 'Dutch',
    nationalityAr: 'هولندي',
    flag: 'https://flagcdn.com/an.svg',
    capital: 'Willemstad',
    fips: 'NT',
    iso2: 'AN',
    iso3: 'ANT',
    isoNo: '530',
    internet: 'AN',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'New Caledonia',
    countryAr: 'كاليدونيا الجديدة',
    nationality: 'New Caledonian',
    nationalityAr: 'كاليدوني',
    flag: 'https://flagcdn.com/nc.svg',
    capital: 'Noumea',
    fips: 'NC',
    iso2: 'NC',
    iso3: 'NCL',
    isoNo: '540',
    internet: 'NC',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'New Zealand',
    countryAr: 'نيوزيلندا',
    nationality: 'New Zealander',
    nationalityAr: 'نيوزيلندي',
    flag: 'https://flagcdn.com/nz.svg',
    capital: 'Wellington',
    fips: 'NZ',
    iso2: 'NZ',
    iso3: 'NZL',
    isoNo: '554',
    internet: 'NZ',
  },
  {
    continent: 'Americas',
    region: 'Central America',
    country: 'Nicaragua',
    countryAr: 'نيكاراغوا',
    nationality: 'Nicaraguan',
    nationalityAr: 'نيكاراغوي',
    flag: 'https://flagcdn.com/ni.svg',
    capital: 'Managua',
    fips: 'NU',
    iso2: 'NI',
    iso3: 'NIC',
    isoNo: '558',
    internet: 'NI',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Niger',
    countryAr: 'النيجر',
    nationality: 'Nigerien',
    nationalityAr: 'نيجيري',
    flag: 'https://flagcdn.com/ne.svg',
    capital: 'Niamey',
    fips: 'NG',
    iso2: 'NE',
    iso3: 'NER',
    isoNo: '562',
    internet: 'NE',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Nigeria',
    countryAr: 'نيجيريا',
    nationality: 'Nigerian',
    nationalityAr: 'نيجيري',
    flag: 'https://flagcdn.com/ng.svg',
    capital: 'Abuja',
    fips: 'NI',
    iso2: 'NG',
    iso3: 'NGA',
    isoNo: '566',
    internet: 'NG',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Niue',
    countryAr: 'نيوي',
    nationality: 'Niuean',
    nationalityAr: 'نيوي',
    flag: 'https://flagcdn.com/nu.svg',
    capital: 'Alofi',
    fips: 'NE',
    iso2: 'NU',
    iso3: 'NIU',
    isoNo: '570',
    internet: 'NU',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Norfolk Island',
    countryAr: 'جزيرة نورفولك',
    nationality: 'Norfolk Islander',
    nationalityAr: 'نورفولكي',
    flag: 'https://flagcdn.com/nf.svg',
    capital: 'Kingston',
    fips: 'NF',
    iso2: 'NF',
    iso3: 'NFK',
    isoNo: '574',
    internet: 'NF',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Northern Mariana Islands',
    countryAr: 'جزر ماريانا الشمالية',
    nationality: 'Northern Mariana Islander',
    nationalityAr: 'مارياني شمالي',
    flag: 'https://flagcdn.com/mp.svg',
    capital: 'Saipan',
    fips: 'CQ',
    iso2: 'MP',
    iso3: 'MNP',
    isoNo: '580',
    internet: 'MP',
  },
  {
    continent: 'Europe',
    region: 'Northern Europe',
    country: 'Norway',
    countryAr: 'النرويج',
    nationality: 'Norwegian',
    nationalityAr: 'نرويجي',
    flag: 'https://flagcdn.com/no.svg',
    capital: 'Oslo',
    fips: 'NO',
    iso2: 'NO',
    iso3: 'NOR',
    isoNo: '578',
    internet: 'NO',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Oman',
    countryAr: 'عمان',
    nationality: 'Omani',
    nationalityAr: 'عماني',
    flag: 'https://flagcdn.com/om.svg',
    capital: 'Muscat',
    fips: 'MU',
    iso2: 'OM',
    iso3: 'OMN',
    isoNo: '512',
    internet: 'OM',
  },
  {
    continent: 'Asia',
    region: 'South Asia',
    country: 'Pakistan',
    countryAr: 'باكستان',
    nationality: 'Pakistani',
    nationalityAr: 'باكستاني',
    flag: 'https://flagcdn.com/pk.svg',
    capital: 'Islamabad',
    fips: 'PK',
    iso2: 'PK',
    iso3: 'PAK',
    isoNo: '586',
    internet: 'PK',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Palau',
    countryAr: 'بالاو',
    nationality: 'Palauan',
    nationalityAr: 'بالاوي',
    flag: 'https://flagcdn.com/pw.svg',
    capital: 'Koror',
    fips: 'PS',
    iso2: 'PW',
    iso3: 'PLW',
    isoNo: '585',
    internet: 'PW',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Palestine',
    countryAr: 'فلسطين',
    nationality: 'Palestinian',
    nationalityAr: 'فلسطيني',
    flag: 'https://flagcdn.com/ps.svg',
    capital: 'East Jerusalem',
    fips: 'WE',
    iso2: 'PS',
    iso3: 'PSE',
    isoNo: '275',
    internet: 'PS',
  },
  {
    continent: 'Americas',
    region: 'Central America',
    country: 'Panama',
    countryAr: 'بنما',
    nationalityAr: 'بنمي',
    nationality: 'Panamanian',
    flag: 'https://flagcdn.com/pa.svg',
    capital: 'Panama',
    fips: 'PM',
    iso2: 'PA',
    iso3: 'PAN',
    isoNo: '591',
    internet: 'PA',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Papua New Guinea',
    countryAr: 'بابوا غينيا الجديدة',
    nationality: 'Papua New Guinean',
    nationalityAr: 'بابوي جديد',
    flag: 'https://flagcdn.com/pg.svg',
    capital: 'Port Moresby',
    fips: 'PP',
    iso2: 'PG',
    iso3: 'PNG',
    isoNo: '598',
    internet: 'PG',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Paraguay',
    countryAr: 'باراغواي',
    nationality: 'Paraguayan',
    nationalityAr: 'باراغوي',
    flag: 'https://flagcdn.com/py.svg',
    capital: 'Asuncion',
    fips: 'PA',
    iso2: 'PY',
    iso3: 'PRY',
    isoNo: '600',
    internet: 'PY',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Peru',
    countryAr: 'بيرو',
    nationality: 'Peruvian',
    nationalityAr: 'بيروفي',
    flag: 'https://flagcdn.com/pe.svg',
    capital: 'Lima',
    fips: 'PE',
    iso2: 'PE',
    iso3: 'PER',
    isoNo: '604',
    internet: 'PE',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Philippines',
    countryAr: 'الفلبين',
    nationality: 'Filipino',
    nationalityAr: 'فلبيني',
    flag: 'https://flagcdn.com/ph.svg',
    capital: 'Manila',
    fips: 'RP',
    iso2: 'PH',
    iso3: 'PHL',
    isoNo: '608',
    internet: 'PH',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Pitcairn Islands',
    countryAr: 'جزر بيتكيرن',
    nationality: 'Pitcairn Islander',
    nationalityAr: 'بيتكيرني',
    flag: 'https://flagcdn.com/pn.svg',
    capital: 'Adamstown',
    fips: 'PC',
    iso2: 'PN',
    iso3: 'PCN',
    isoNo: '612',
    internet: 'PN',
  },
  {
    continent: 'Europe',
    region: 'Eastern Europe',
    country: 'Poland',
    countryAr: 'بولندا',
    nationality: 'Polish',
    nationalityAr: 'بولندي',
    flag: 'https://flagcdn.com/pl.svg',
    capital: 'Warsaw',
    fips: 'PL',
    iso2: 'PL',
    iso3: 'POL',
    isoNo: '616',
    internet: 'PL',
  },
  {
    continent: 'Europe',
    region: 'South West Europe',
    country: 'Portugal',
    countryAr: 'البرتغال',
    nationality: 'Portuguese',
    nationalityAr: 'برتغالي',
    flag: 'https://flagcdn.com/pt.svg',
    capital: 'Lisbon',
    fips: 'PO',
    iso2: 'PT',
    iso3: 'PRT',
    isoNo: '620',
    internet: 'PT',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Puerto Rico',
    countryAr: 'بورتوريكو',
    nationality: 'Puerto Rican',
    nationalityAr: 'بورتوريكي',
    flag: 'https://flagcdn.com/pr.svg',
    capital: 'San Juan',
    fips: 'RQ',
    iso2: 'PR',
    iso3: 'PRI',
    isoNo: '630',
    internet: 'PR',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Qatar',
    countryAr: 'قطر',
    nationality: 'Qatari',
    nationailtyAr: 'قطري',
    flag: 'https://flagcdn.com/qa.svg',
    capital: 'Doha',
    fips: 'QA',
    iso2: 'QA',
    iso3: 'QAT',
    isoNo: '634',
    internet: 'QA',
  },
  {
    continent: 'Africa',
    region: 'Indian Ocean',
    country: 'Reunion',
    countryAr: 'ريونيون',
    nationality: 'Reunionese',
    nationalityAr: 'ريوني',
    flag: 'https://flagcdn.com/re.svg',
    capital: 'Saint-Denis',
    fips: 'RE',
    iso2: 'RE',
    iso3: 'REU',
    isoNo: '638',
    internet: 'RE',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'Romania',
    countryAr: 'رومانيا',
    nationality: 'Romanian',
    nationalityAr: 'روماني',
    flag: 'https://flagcdn.com/ro.svg',
    capital: 'Bucharest',
    fips: 'RO',
    iso2: 'RO',
    iso3: 'ROU',
    isoNo: '642',
    internet: 'RO',
  },
  {
    continent: 'Asia',
    region: 'Northern Asia',
    country: 'Russia',
    countryAr: 'روسيا',
    nationality: 'Russian',
    nationalityAr: 'روسي',
    flag: 'https://flagcdn.com/ru.svg',
    capital: 'Moscow',
    fips: 'RS',
    iso2: 'RU',
    iso3: 'RUS',
    isoNo: '643',
    internet: 'RU',
  },
  {
    continent: 'Africa',
    region: 'Central Africa',
    country: 'Rwanda',
    countryAr: 'رواندا',
    nationality: 'Rwandan',
    nationalityAr: 'رواندي',
    flag: 'https://flagcdn.com/rw.svg',
    capital: 'Kigali',
    fips: 'RW',
    iso2: 'RW',
    iso3: 'RWA',
    isoNo: '646',
    internet: 'RW',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Saint Kitts and Nevis',
    countryAr: 'سانت كيتس ونيفيس',
    nationality: 'Kittitian or Nevisian',
    nationalityAr: 'كيتسي أو نيفيسي',
    flag: 'https://flagcdn.com/kn.svg',
    capital: 'Basseterre',
    fips: 'SC',
    iso2: 'KN',
    iso3: 'KNA',
    isoNo: '659',
    internet: 'KN',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Saint Lucia',
    countryAr: 'سانت لوسيا',
    nationality: 'Saint Lucian',
    nationalityAr: 'سانت لوسي',
    flag: 'https://flagcdn.com/lc.svg',
    capital: 'Castries',
    fips: 'ST',
    iso2: 'LC',
    iso3: 'LCA',
    isoNo: '662',
    internet: 'LC',
  },
  {
    continent: 'Americas',
    region: 'North America',
    country: 'Saint Pierre and Miquelon',
    countryAr: 'سانت بيير وميكلون',
    nationality: 'Saint-Pierrais or Miquelonnais',
    nationalityAr: 'سانت بييري أو ميكلوني',
    flag: 'https://flagcdn.com/pm.svg',
    capital: 'Saint-Pierre',
    fips: 'SB',
    iso2: 'PM',
    iso3: 'SPM',
    isoNo: '666',
    internet: 'PM',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Saint Vincent and the Grenadines',
    countryAr: 'سانت فنسنت وجزر غرينادين',
    nationality: 'Saint Vincentian',
    nationalityAr: 'سانت فنسنتي',
    flag: 'https://flagcdn.com/vc.svg',
    capital: 'Kingstown',
    fips: 'VC',
    iso2: 'VC',
    iso3: 'VCT',
    isoNo: '670',
    internet: 'VC',
  },
  {
    continent: 'Europe',
    region: 'Southern Europe',
    country: 'San Marino',
    countryAr: 'سان مارينو',
    nationality: 'San Marinese',
    nationalityAr: 'سان ماريني',
    flag: 'https://flagcdn.com/sm.svg',
    capital: 'San Marino',
    fips: 'SM',
    iso2: 'SM',
    iso3: 'SMR',
    isoNo: '674',
    internet: 'SM',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Sao Tome and Principe',
    countryAr: 'ساو تومي وبرينسيب',
    nationality: 'Sao Tomean',
    nationalityAr: 'ساو توميان',
    flag: 'https://flagcdn.com/st.svg',
    capital: 'Sao Tome',
    fips: 'TP',
    iso2: 'ST',
    iso3: 'STP',
    isoNo: '678',
    internet: 'ST',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Saudi Arabia',
    countryAr: 'السعودية',
    nationality: 'Saudi',
    nationalityAr: 'سعودي',
    flag: 'https://flagcdn.com/sa.svg',
    capital: 'Riyadh',
    fips: 'SA',
    iso2: 'SA',
    iso3: 'SAU',
    isoNo: '682',
    internet: 'SA',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Senegal',
    countryAr: 'السنغال',
    nationality: 'Senegalese',
    nationalityAr: 'سنغالي',
    flag: 'https://flagcdn.com/sn.svg',
    capital: 'Dakar',
    fips: 'SG',
    iso2: 'SN',
    iso3: 'SEN',
    isoNo: '686',
    internet: 'SN',
  },
  {
    continent: 'Africa',
    region: 'Indian Ocean',
    country: 'Seychelles',
    countryAr: 'سيشل',
    nationality: 'Seychello',
    nationalityAr: 'سيشلي',
    flag: 'https://flagcdn.com/sc.svg',
    capital: 'Victoria',
    fips: 'SE',
    iso2: 'SC',
    iso3: 'SYC',
    isoNo: '690',
    internet: 'SC',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Sierra Leone',
    countryAr: 'سيراليون',
    nationality: 'Sierra Leonean',
    nationalityAr: 'سيراليوني',
    flag: 'https://flagcdn.com/sl.svg',
    capital: 'Freetown',
    fips: 'SL',
    iso2: 'SL',
    iso3: 'SLE',
    isoNo: '694',
    internet: 'SL',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Singapore',
    countryAr: 'سنغافورة',
    nationality: 'Singaporean',
    nationalityAr: 'سنغافوري',
    flag: 'https://flagcdn.com/sg.svg',
    capital: 'Singapore',
    fips: 'SN',
    iso2: 'SG',
    iso3: 'SGP',
    isoNo: '702',
    internet: 'SG',
  },
  {
    continent: 'Europe',
    region: 'Central Europe',
    country: 'Slovakia',
    countryAr: 'سلوفاكيا',
    nationality: 'Slovak',
    nationalityAr: 'سلوفاكي',
    flag: 'https://flagcdn.com/sk.svg',
    capital: 'Bratislava',
    fips: 'LO',
    iso2: 'SK',
    iso3: 'SVK',
    isoNo: '703',
    internet: 'SK',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'Slovenia',
    countryAr: 'سلوفينيا',
    nationality: 'Slovenian',
    nationalityAr: 'سلوفيني',
    flag: 'https://flagcdn.com/si.svg',
    capital: 'Ljubljana',
    fips: 'SI',
    iso2: 'SI',
    iso3: 'SVN',
    isoNo: '705',
    internet: 'SI',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Solomon Islands',
    countryAr: 'جزر سليمان',
    nationality: 'Solomon Islander',
    nationalityAr: 'سليماني',
    flag: 'https://flagcdn.com/sb.svg',
    capital: 'Honiara',
    fips: 'BP',
    iso2: 'SB',
    iso3: 'SLB',
    isoNo: '090',
    internet: 'SB',
  },
  {
    continent: 'Africa',
    region: 'Eastern Africa',
    country: 'Somalia',
    countryAr: 'الصومال',
    nationality: 'Somali',
    nationalityAr: 'صومالي',
    flag: 'https://flagcdn.com/so.svg',
    capital: 'Mogadishu',
    fips: 'SO',
    iso2: 'SO',
    iso3: 'SOM',
    isoNo: '706',
    internet: 'SO',
  },
  {
    continent: 'Africa',
    region: 'Southern Africa',
    country: 'South Africa',
    countryAr: 'جنوب أفريقيا',
    nationality: 'South African',
    nationalityAr: 'جنوب أفريقي',
    flag: 'https://flagcdn.com/za.svg',
    capital: 'Pretoria��',
    fips: 'SF',
    iso2: 'ZA',
    iso3: 'ZAF',
    isoNo: '710',
    internet: 'ZA',
  },
  {
    continent: 'Europe',
    region: 'South West Europe',
    country: 'Spain',
    countryAr: 'إسبانيا',
    nationality: 'Spanish',
    nationalityAr: 'إسباني',
    flag: 'https://flagcdn.com/es.svg',
    capital: 'Madrid',
    fips: 'SP',
    iso2: 'ES',
    iso3: 'ESP',
    isoNo: '724',
    internet: 'ES',
  },
  {
    continent: 'Asia',
    region: 'South Asia',
    country: 'Sri Lanka',
    countryAr: 'سريلانكا',
    nationality: 'Sri Lankan',
    nationalityAr: 'سريلانكي',
    flag: 'https://flagcdn.com/lk.svg',
    capital: 'Colombo',
    fips: 'CE',
    iso2: 'LK',
    iso3: 'LKA',
    isoNo: '144',
    internet: 'LK',
  },
  {
    continent: 'Africa',
    region: 'Northern Africa',
    country: 'Sudan',
    countryAr: 'السودان',
    nationality: 'Sudanese',
    nationalityAr: 'سوداني',
    flag: 'https://flagcdn.com/sd.svg',
    capital: 'Khartoum',
    fips: 'SU',
    iso2: 'SD',
    iso3: 'SDN',
    isoNo: '729',
    internet: 'SD',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Suriname',
    countryAr: 'سورينام',
    nationality: 'Surinamese',
    nationalityAr: 'سورينامي',
    flag: 'https://flagcdn.com/sr.svg',
    capital: 'Paramaribo',
    fips: 'NS',
    iso2: 'SR',
    iso3: 'SUR',
    isoNo: '740',
    internet: 'SR',
  },
  {
    continent: 'Europe',
    region: 'Northern Europe',
    country: 'Svalbard',
    countryAr: 'سفالبارد',
    nationality: 'Svalbardian',
    nationalityAr: 'سفالباردي',
    flag: 'https://flagcdn.com/sj.svg',
    capital: 'Longyearbyen',
    fips: 'SV',
    iso2: 'SJ',
    iso3: 'SJM',
    isoNo: '744',
    internet: 'SJ',
  },
  {
    continent: 'Africa',
    region: 'Southern Africa',
    country: 'Eswatini',
    countryAr: 'إسواتيني',
    nationality: 'Swazi',
    nationalityAr: 'سوازي',
    flag: 'https://flagcdn.com/sz.svg',
    capital: 'Mbabane',
    fips: 'WZ',
    iso2: 'SZ',
    iso3: 'SWZ',
    isoNo: '748',
    internet: 'SZ',
  },
  {
    continent: 'Europe',
    region: 'Northern Europe',
    country: 'Sweden',
    countryAr: 'السويد',
    nationality: 'Swedish',
    nationalityAr: 'سويدي',
    flag: 'https://flagcdn.com/se.svg',
    capital: 'Stockholm',
    fips: 'SW',
    iso2: 'SE',
    iso3: 'SWE',
    isoNo: '752',
    internet: 'SE',
  },
  {
    continent: 'Europe',
    region: 'Central Europe',
    country: 'Switzerland',
    countryAr: 'سويسرا',
    nationality: 'Swiss',
    nationalityAr: 'سويسري',
    flag: 'https://flagcdn.com/ch.svg',
    capital: 'Bern',
    fips: 'SZ',
    iso2: 'CH',
    iso3: 'CHE',
    isoNo: '756',
    internet: 'CH',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Syria',
    countryAr: 'سوريا',
    nationality: 'Syrian',
    nationalityAr: 'سوري',
    flag: 'https://flagcdn.com/sy.svg',
    capital: 'Damascus',
    fips: 'SY',
    iso2: 'SY',
    iso3: 'SYR',
    isoNo: '760',
    internet: 'SY',
  },
  {
    continent: 'Asia',
    region: 'East Asia',
    country: 'Taiwan',
    countryAr: 'تايوان',
    nationality: 'Taiwanese',
    nationalityAr: 'تايواني',
    flag: 'https://flagcdn.com/tw.svg',
    capital: 'Taipei',
    fips: 'TW',
    iso2: 'TW',
    iso3: 'TWN',
    isoNo: '158',
    internet: 'TW',
  },
  {
    continent: 'Asia',
    region: 'Central Asia',
    country: 'Tajikistan',
    countryAr: 'طاجيكستان',
    nationality: 'Tajik',
    nationalityAr: 'طاجيكي',
    flag: 'https://flagcdn.com/tj.svg',
    capital: 'Dushanbe',
    fips: 'TI',
    iso2: 'TJ',
    iso3: 'TJK',
    isoNo: '762',
    internet: 'TJ',
  },
  {
    continent: 'Africa',
    region: 'Eastern Africa',
    country: 'Tanzania',
    countryAr: 'تنزانيا',
    nationality: 'Tanzanian',
    nationalityAr: 'تنزاني',
    flag: 'https://flagcdn.com/tz.svg',
    capital: 'Dar es Salaam',
    fips: 'TZ',
    iso2: 'TZ',
    iso3: 'TZA',
    isoNo: '834',
    internet: 'TZ',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Thailand',
    countryAr: 'تايلاند',
    nationality: 'Thai',
    nationalityAr: 'تايلاندي',
    flag: 'https://flagcdn.com/th.svg',
    capital: 'Bangkok',
    fips: 'TH',
    iso2: 'TH',
    iso3: 'THA',
    isoNo: '764',
    internet: 'TH',
  },
  {
    continent: 'Africa',
    region: 'Western Africa',
    country: 'Togo',
    countryAr: 'توغو',
    nationality: 'Togolese',
    nationalityAr: 'توغوي',
    flag: 'https://flagcdn.com/tg.svg',
    capital: 'Lome',
    fips: 'TO',
    iso2: 'TG',
    iso3: 'TGO',
    isoNo: '768',
    internet: 'TG',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Tokelau',
    countryAr: 'توكيلاو',
    nationality: 'Tokelauan',
    nationalityAr: 'توكيلوي',
    flag: 'https://flagcdn.com/tk.svg',
    capital: 'none',
    fips: 'TL',
    iso2: 'TK',
    iso3: 'TKL',
    isoNo: '772',
    internet: 'TK',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Tonga',
    countryAr: 'تونغا',
    nationality: 'Tongan',
    nationalityAr: 'تونغي',
    flag: 'https://flagcdn.com/to.svg',
    capital: "Nuku'alofa",
    fips: 'TN',
    iso2: 'TO',
    iso3: 'TON',
    isoNo: '776',
    internet: 'TO',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Trinidad and Tobago',
    countryAr: 'ترينيداد وتوباغو',
    nationality: 'Trinidadian or Tobagonian',
    nationalityAr: 'ترينيدادي أو توباغي',
    flag: 'https://flagcdn.com/tt.svg',
    capital: 'Port-of-Spain',
    fips: 'TD',
    iso2: 'TT',
    iso3: 'TTO',
    isoNo: '780',
    internet: 'TT',
  },
  {
    continent: 'Africa',
    region: 'Northern Africa',
    country: 'Tunisia',
    countryAr: 'تونس',
    nationality: 'Tunisian',
    nationalityAr: 'تونسي',
    flag: 'https://flagcdn.com/tn.svg',
    capital: 'Tunis',
    fips: 'TS',
    iso2: 'TN',
    iso3: 'TUN',
    isoNo: '788',
    internet: 'TN',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Turkey',
    countryAr: 'تركيا',
    nationality: 'Turkish',
    nationalityAr: 'تركي',
    flag: 'https://flagcdn.com/tr.svg',
    capital: 'Ankara',
    fips: 'TU',
    iso2: 'TR',
    iso3: 'TUR',
    isoNo: '792',
    internet: 'TR',
  },
  {
    continent: 'Asia',
    region: 'Central Asia',
    country: 'Turkmenistan',
    countryAr: 'تركمانستان',
    nationality: 'Turkmen',
    nationalityAr: 'تركماني',
    flag: 'https://flagcdn.com/tm.svg',
    capital: 'Ashgabat',
    fips: 'TX',
    iso2: 'TM',
    iso3: 'TKM',
    isoNo: '795',
    internet: 'TM',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Turks and Caicos Islands',
    countryAr: 'جزر تركس وكايكوس',
    nationality: 'Turks and Caicos Islander',
    nationalityAr: 'تركسي وكايكوسي',
    flag: 'https://flagcdn.com/tc.svg',
    capital: 'Grand Turk',
    fips: 'TK',
    iso2: 'TC',
    iso3: 'TCA',
    isoNo: '796',
    internet: 'TC',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Tuvalu',
    countryAr: 'توفالو',
    nationality: 'Tuvaluan',
    nationalityAr: 'توفالوي',
    flag: 'https://flagcdn.com/tv.svg',
    capital: 'Funafuti',
    fips: 'TV',
    iso2: 'TV',
    iso3: 'TUV',
    isoNo: '798',
    internet: 'TV',
  },
  {
    continent: 'Africa',
    region: 'Eastern Africa',
    country: 'Uganda',
    countryAr: 'أوغندا',
    nationality: 'Ugandan',
    nationalityAr: 'أوغندي',
    flag: 'https://flagcdn.com/ug.svg',
    capital: 'Kampala',
    fips: 'UG',
    iso2: 'UG',
    iso3: 'UGA',
    isoNo: '800',
    internet: 'UG',
  },
  {
    continent: 'Europe',
    region: 'Eastern Europe',
    country: 'Ukraine',
    countryAr: 'أوكرانيا',
    nationality: 'Ukrainian',
    nationalityAr: 'أوكراني',
    flag: 'https://flagcdn.com/ua.svg',
    capital: 'Kyiv',
    fips: 'UP',
    iso2: 'UA',
    iso3: 'UKR',
    isoNo: '804',
    internet: 'UA',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'United Arab Emirates',
    countryAr: 'الإمارات العربية المتحدة',
    nationality: 'Emirati',
    nationalityAr: 'إماراتي',
    flag: 'https://flagcdn.com/ae.svg',
    capital: 'Abu Dhabi',
    fips: 'TC',
    iso2: 'AE',
    iso3: 'ARE',
    isoNo: '784',
    internet: 'AE',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'United Kingdom',
    countryAr: 'المملكة المتحدة',
    nationality: 'British',
    nationalityAr: 'بريطاني',
    flag: 'https://flagcdn.com/gb.svg',
    capital: 'London',
    fips: 'UK',
    iso2: 'GB',
    iso3: 'GBR',
    isoNo: '826',
    internet: 'UK',
  },
  {
    continent: 'Americas',
    region: 'North America',
    country: 'United States',
    countryAr: 'الولايات المتحدة',
    nationality: 'American',
    nationalityAr: 'أمريكي',
    flag: 'https://flagcdn.com/us.svg',
    capital: 'Washington DC',
    fips: 'US',
    iso2: 'US',
    iso3: 'USA',
    isoNo: '840',
    internet: 'US',
  },
  {
    continent: 'Americas',
    region: 'North America',
    country: 'United States Minor Outlying Islands',
    countryAr: 'جزر الولايات المتحدة البعيدة الصغيرة',
    nationality: 'American',
    nationalityAr: 'أمريكي',
    flag: 'https://flagcdn.com/um.svg',
    capital: 'Washington DC',
    fips: '',
    iso2: 'UM',
    iso3: 'UMI',
    isoNo: '581',
    internet: 'US',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Uruguay',
    countryAr: 'أوروغواي',
    nationality: 'Uruguayan',
    nationalityAr: 'أوروغوي',
    flag: 'https://flagcdn.com/uy.svg',
    capital: 'Montevideo',
    fips: 'UY',
    iso2: 'UY',
    iso3: 'URY',
    isoNo: '858',
    internet: 'UY',
  },
  {
    continent: 'Asia',
    region: 'Central Asia',
    country: 'Uzbekistan',
    countryAr: 'أوزبكستان',
    nationality: 'Uzbek',
    nationalityAr: 'أوزبكي',
    flag: 'https://flagcdn.com/uz.svg',
    capital: 'Tashkent (Toshkent)',
    fips: 'UZ',
    iso2: 'UZ',
    iso3: 'UZB',
    isoNo: '860',
    internet: 'UZ',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Vanuatu',
    countryAr: 'فانواتو',
    nationality: 'Vanuatuan',
    nationalityAr: 'فانواتوي',
    flag: 'https://flagcdn.com/vu.svg',
    capital: 'Port-Vila',
    fips: 'NH',
    iso2: 'VU',
    iso3: 'VUT',
    isoNo: '548',
    internet: 'VU',
  },
  {
    continent: 'Americas',
    region: 'South America',
    country: 'Venezuela',
    countryAr: 'فنزويلا',
    nationality: 'Venezuelan',
    nationalityAr: 'فنزويلي',
    flag: 'https://flagcdn.com/ve.svg',
    capital: 'Caracas',
    fips: 'VE',
    iso2: 'VE',
    iso3: 'VEN',
    isoNo: '862',
    internet: 'UE',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Vietnam',
    countryAr: 'فيتنام',
    nationality: 'Vietnamese',
    nationalityAr: 'فيتنامي',
    flag: 'https://flagcdn.com/vn.svg',
    capital: 'Hanoi',
    fips: 'VN',
    iso2: 'VN',
    iso3: 'VNM',
    isoNo: '704',
    internet: 'VN',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Virgin Islands',
    countryAr: 'جزر العذراء',
    nationality: 'Virgin Islander',
    nationalityAr: 'عذراءي',
    flag: 'https://flagcdn.com/vi.svg',
    capital: 'Charlotte Amalie',
    fips: 'VQ',
    iso2: 'VI',
    iso3: 'VIR',
    isoNo: '850',
    internet: 'VI',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Wallis and Futuna',
    countryAr: 'والس وفوتونا',
    nationality: 'Wallis and Futuna Islander',
    nationalityAr: 'والسي وفوتوني',
    flag: 'https://flagcdn.com/wf.svg',
    capital: 'Mata-Utu (on Ile Uvea)',
    fips: 'WF',
    iso2: 'WF',
    iso3: 'WLF',
    isoNo: '876',
    internet: 'WF',
  },
  {
    continent: 'Africa',
    region: 'Northern Africa',
    country: 'Western Sahara',
    countryAr: 'الصحراء الغربية',
    nationality: 'Sahrawi',
    nationalityAr: 'صحراوي',
    flag: 'https://flagcdn.com/eh.svg',
    capital: 'none',
    fips: 'WI',
    iso2: 'EH',
    iso3: 'ESH',
    isoNo: '732',
    internet: 'EH',
  },
  {
    continent: 'Oceania',
    region: 'Pacific',
    country: 'Western Samoa',
    countryAr: 'ساموا الغربية',
    nationality: 'Samoan',
    nationalityAr: 'ساموي',
    flag: 'https://flagcdn.com/ws.svg',
    capital: 'Apia',
    fips: 'WS',
    iso2: 'WS',
    iso3: 'WSM',
    isoNo: '882',
    internet: 'WS',
  },
  {
    continent: 'Asia',
    region: 'South West Asia',
    country: 'Yemen',
    countryAr: 'اليمن',
    nationality: 'Yemeni',
    nationalityAr: 'يمني',
    flag: 'https://flagcdn.com/ye.svg',
    capital: 'Sanaa',
    fips: 'YM',
    iso2: 'YE',
    iso3: 'YEM',
    isoNo: '887',
    internet: 'YE',
  },
  {
    continent: 'Africa',
    region: 'Central Africa',
    country: 'Democratic Republic of the Congo',
    countryAr: 'جمهورية الكونغو الديمقراطية',
    nationality: 'Congolese',
    nationalityAr: 'كونغولي',
    flag: 'https://flagcdn.com/cd.svg',
    capital: 'Kinshasa',
    fips: 'CG',
    iso2: 'CD',
    iso3: 'COD',
    isoNo: '180',
    internet: 'ZR',
  },
  {
    continent: 'Africa',
    region: 'Southern Africa',
    country: 'Zambia',
    countryAr: 'زامبيا',
    nationality: 'Zambian',
    nationalityAr: 'زامبي',
    flag: 'https://flagcdn.com/zm.svg',
    capital: 'Lusaka',
    fips: 'ZA',
    iso2: 'ZM',
    iso3: 'ZMB',
    isoNo: '894',
    internet: 'ZM',
  },
  {
    continent: 'Africa',
    region: 'Southern Africa',
    country: 'Zimbabwe',
    countryAr: 'زيمبابوي',
    nationality: 'Zimbabwean',
    nationalityAr: 'زيمبابوي',
    flag: 'https://flagcdn.com/zw.svg',
    capital: 'Harare',
    fips: 'ZI',
    iso2: 'ZW',
    iso3: 'ZWE',
    isoNo: '716',
    internet: 'ZW',
  },
  {
    continent: 'Asia',
    region: 'East Asia',
    country: 'Hong Kong',
    countryAr: 'هونغ كونغ',
    nationality: 'Hong Konger',
    nationalityAr: 'هونغ كونغي',
    flag: 'https://flagcdn.com/hk.svg',
    capital: 'Victoria',
    fips: 'HK',
    iso2: 'HK',
    iso3: 'HKG',
    isoNo: '344',
    internet: 'HK',
  },
  {
    continent: 'Asia',
    region: 'East Asia',
    country: 'Macau',
    countryAr: 'ماكاو',
    nationality: 'Macanese',
    nationalityAr: 'ماكاوي',
    flag: 'https://flagcdn.com/mo.svg',
    capital: 'Macau',
    fips: 'MC',
    iso2: 'MO',
    iso3: 'MAC',
    isoNo: '446',
    internet: 'MO',
  },
  {
    continent: 'Antarctica',
    region: 'Antarctica',
    country: 'Antarctica',
    countryAr: 'القارة القطبية الجنوبية',
    nationalityAr: 'قاريء قطبي جنوبي',
    nationality: 'Antarctican',
    flag: 'https://flagcdn.com/aq.svg',
    capital: 'none',
    fips: 'AY',
    iso2: 'AQ',
    iso3: 'ATA',
    isoNo: '010',
    internet: 'AQ',
  },
  {
    continent: 'Atlantic Ocean',
    region: 'South Atlantic Ocean',
    country: 'Bouvet Island',
    countryAr: 'جزيرة بوفيه',
    nationality: 'Norwegian',
    nationalityAr: 'نرويجي',
    flag: 'https://flagcdn.com/bv.svg',
    capital: 'none',
    fips: 'BV',
    iso2: 'BV',
    iso3: 'BVT',
    isoNo: '074',
    internet: 'BV',
  },
  {
    continent: 'Asia',
    region: 'South Asia',
    country: 'British Indian Ocean Territory',
    countryAr: 'إقليم المحيط الهندي البريطاني',
    nationality: 'British',
    nationalityAr: 'بريطاني',
    flag: 'https://flagcdn.com/io.svg',
    capital: '',
    fips: 'IO',
    iso2: 'IO',
    iso3: 'IOT',
    isoNo: '086',
    internet: 'IO',
  },
  {
    continent: 'Indian Ocean',
    region: 'Southern Indian Ocean',
    country: 'French Southern and Antarctic Lands',
    countryAr: 'الأراضي الفرنسية الجنوبية والأنتارتيكية',
    nationality: 'French',
    nationalityAr: 'فرنسي',
    flag: 'https://flagcdn.com/tf.svg',
    capital: '',
    fips: 'FS',
    iso2: 'TF',
    iso3: 'ATF',
    isoNo: '260',
    internet: '--',
  },
  {
    continent: 'Indian Ocean',
    region: 'Southern Indian Ocean',
    country: 'Heard Island and McDonald Islands',
    countryAr: 'جزيرة هيرد وجزر ماكدونالد',
    nationality: 'Australian',
    nationalityAr: 'أسترالي',
    flag: 'https://flagcdn.com/hm.svg',
    capital: '',
    fips: 'HM',
    iso2: 'HM',
    iso3: 'HMD',
    isoNo: '334',
    internet: 'HM',
  },
  {
    continent: 'Atlantic Ocean',
    region: 'South Atlantic Ocean',
    country: 'Saint Helena',
    countryAr: 'سانت هيلينا',
    nationality: 'Saint Helenian',
    nationalityAr: 'سانت هيليني',
    flag: 'https://flagcdn.com/sh.svg',
    capital: '',
    fips: 'SH',
    iso2: 'SH',
    iso3: 'SHN',
    isoNo: '654',
    internet: 'SH',
  },
  {
    continent: 'Atlantic Ocean',
    region: 'South Atlantic Ocean',
    country: 'South Georgia and the South Sandwich Islands',
    countryAr: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
    nationality: 'British',
    nationalityAr: 'بريطاني',
    flag: 'https://flagcdn.com/gs.svg',
    capital: '',
    fips: 'SX',
    iso2: 'GS',
    iso3: 'SGS',
    isoNo: '239',
    internet: 'GS',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'Guernsey',
    countryAr: 'غيرنزي',
    nationality: 'British',
    nationalityAr: 'بريطاني',
    flag: 'https://flagcdn.com/gg.svg',
    capital: 'Saint Peter Port',
    fips: 'GK',
    iso2: 'GG',
    iso3: 'GGY',
    isoNo: '831',
    internet: 'GG',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'Serbia',
    countryAr: 'صربيا',
    nationality: 'Serbian',
    nationalityAr: 'صربي',
    flag: 'https://flagcdn.com/rs.svg',
    capital: 'Belgrade',
    fips: 'RI',
    iso2: 'RS',
    iso3: 'SRB',
    isoNo: '688',
    internet: 'RS',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Saint Barthélemy',
    countryAr: 'سان بارتيلمي',
    nationality: 'French',
    nationalityAr: 'فرنسي',
    flag: 'https://flagcdn.com/bl.svg',
    capital: 'Gustavia',
    fips: 'TB',
    iso2: 'BL',
    iso3: 'BLM',
    isoNo: '652',
    internet: 'BL',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'Montenegro',
    countryAr: 'الجبل الأسود',
    nationality: 'Montenegrin',
    nationalityAr: 'مونتينيغري',
    flag: 'https://flagcdn.com/me.svg',
    capital: 'Podgorica',
    fips: 'MJ',
    iso2: 'ME',
    iso3: 'MNE',
    isoNo: '499',
    internet: 'ME',
  },
  {
    continent: 'Europe',
    region: 'Western Europe',
    country: 'Jersey',
    countryAr: 'جيرسي',
    nationality: 'British',
    nationalityAr: 'بريطاني',
    flag: 'https://flagcdn.com/je.svg',
    capital: 'Saint Helier',
    fips: 'JE',
    iso2: 'JE',
    iso3: 'JEY',
    isoNo: '832',
    internet: 'JE',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Curaçao',
    countryAr: 'كوراساو',
    nationality: 'Dutch',
    nationalityAr: 'هولندي',
    flag: 'https://flagcdn.com/cw.svg',
    capital: 'Willemstad',
    fips: 'UC',
    iso2: 'CW',
    iso3: 'CUW',
    isoNo: '531',
    internet: 'CW',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Saint Martin',
    nationality: 'French',
    nationalityAr: 'فرنسي',
    countryAr: 'سانت مارتن',
    flag: 'https://flagcdn.com/mf.svg',
    capital: 'Marigot',
    fips: 'RN',
    iso2: 'MF',
    iso3: 'MAF',
    isoNo: '663',
    internet: 'MF',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Sint Maarten',
    nationality: 'Dutch',
    nationalityAr: 'هولندي',
    countryAr: 'سانت مارتن',
    flag: 'https://flagcdn.com/sx.svg',
    capital: 'Philipsburg',
    fips: 'NN',
    iso2: 'SX',
    iso3: 'SXM',
    isoNo: '534',
    internet: 'SX',
  },
  {
    continent: 'Asia',
    region: 'South East Asia',
    country: 'Timor-Leste',
    countryAr: 'تيمور الشرقية',
    nationality: 'Timorese',
    nationalityAr: 'تيموري',
    flag: 'https://flagcdn.com/tl.svg',
    capital: 'Dili',
    fips: 'TT',
    iso2: 'TL',
    iso3: 'TLS',
    isoNo: '626',
    internet: 'TL',
  },
  {
    continent: 'Africa',
    region: 'Northern Africa',
    country: 'South Sudan',
    nationality: 'South Sudanese',
    nationalityAr: 'جنوب السودان',
    countryAr: 'جنوب السودان',
    flag: 'https://flagcdn.com/ss.svg',
    capital: 'Juba',
    fips: 'OD',
    iso2: 'SS',
    iso3: 'SSD',
    isoNo: '728',
    internet: 'SS',
  },
  {
    continent: 'Europe',
    region: 'Northern Europe',
    country: 'Åland Islands',
    nationality: 'Åland Islander',
    nationalityAr: 'جزر أولاند',
    countryAr: 'جزر أولاند',
    flag: 'https://flagcdn.com/ax.svg',
    capital: 'Mariehamn',
    fips: 'AX',
    iso2: 'AX',
    iso3: 'ALA',
    isoNo: '248',
    internet: 'AX',
  },
  {
    continent: 'Americas',
    region: 'West Indies',
    country: 'Bonaire',
    nationality: 'Dutch',
    nationalityAr: 'هولندي',
    countryAr: 'بونير',
    flag: 'https://flagcdn.com/bq.svg',
    capital: 'Kralendijk',
    fips: 'BQ',
    iso2: 'BQ',
    iso3: 'BES',
    isoNo: '535',
    internet: 'BQ',
  },
  {
    continent: 'Europe',
    region: 'South East Europe',
    country: 'Republic of Kosovo',
    nationality: 'Kosovar',
    nationalityAr: 'كوسوفي',
    countryAr: 'كوسوفو',
    flag: 'https://flagcdn.com/xk.svg',
    capital: 'Pristina',
    fips: 'KV',
    iso2: 'XK',
    iso3: 'XKX',
    isoNo: null,
    internet: 'XK',
  },
];
export function countryNameValidation() {
  return countries.map((country) => country.country);
}

export function nationalityValidation() {
  return countries.map((country) => country.nationality);
}

export function countryIso2Validation() {
  return countries.map((country) => country.iso2);
}

export function searchByKeyAndValue(key: string, value: string) {
  return countries.find((country) => country[key] === value) ?? null;
}

export function getCountryByIso(iso: string) {
  if (!isNaN(parseInt(iso)))
    return searchByKeyAndValue(
      'isoNo',
      ('00' + parseInt(iso).toString()).slice(-3),
    );

  return searchByKeyAndValue(`iso${iso.length}`, iso.toUpperCase());
}

export function getCountryCallingCodeByIso2(countryIso2: string) {
  try {
    return getCountryCallingCode(countryIso2 as CountryCode);
  } catch {
    return null;
  }
}

export function detectCountry(phone: string, translate: any) {
  const phoneNumber = parsePhoneNumber(phone);
  if (!phoneNumber)
    return translate(BadRequestException, 'USER.INVALID_MOBILE_NUMBER');
  if (!phoneNumber.isValid())
    return translate(BadRequestException, 'USER.INVALID_MOBILE_NUMBER');
  const res = searchByKeyAndValue('internet', phoneNumber.country as string);
  if (!res) return translate(NotFoundException, 'COUNTRY.COUNTRY_NOT_FOUND');

  return {
    ...res,
    nationalNumber: phoneNumber.nationalNumber,
  };
}
